// Mocks generated by Mockito 5.4.4 from annotations
// in weather_app/test/data/datasources/remote/weather_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core/data/data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0 extends _i1.SmartFake implements _i2.HttpResponse {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockIHttpClient extends _i1.Mock implements _i2.IHttpClient {
  MockIHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.HttpResponse> get(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    Duration? timeout,
    String? apiVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #headers: headers,
            #query: query,
            #timeout: timeout,
            #apiVersion: apiVersion,
          },
        ),
        returnValue: _i3.Future<_i2.HttpResponse>.value(_FakeHttpResponse_0(
          this,
          Invocation.method(
            #get,
            [url],
            {
              #headers: headers,
              #query: query,
              #timeout: timeout,
              #apiVersion: apiVersion,
            },
          ),
        )),
      ) as _i3.Future<_i2.HttpResponse>);

  @override
  _i3.Future<_i2.HttpResponse> post(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    Duration? timeout,
    String? apiVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #apiVersion: apiVersion,
          },
        ),
        returnValue: _i3.Future<_i2.HttpResponse>.value(_FakeHttpResponse_0(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #apiVersion: apiVersion,
            },
          ),
        )),
      ) as _i3.Future<_i2.HttpResponse>);

  @override
  _i3.Future<_i2.HttpResponse> put(
    String? url, {
    Map<String, String>? headers,
    dynamic body,
    Duration? timeout,
    String? apiVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #apiVersion: apiVersion,
          },
        ),
        returnValue: _i3.Future<_i2.HttpResponse>.value(_FakeHttpResponse_0(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #apiVersion: apiVersion,
            },
          ),
        )),
      ) as _i3.Future<_i2.HttpResponse>);

  @override
  _i3.Future<_i2.HttpResponse> patch(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    Duration? timeout,
    String? apiVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #apiVersion: apiVersion,
          },
        ),
        returnValue: _i3.Future<_i2.HttpResponse>.value(_FakeHttpResponse_0(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #apiVersion: apiVersion,
            },
          ),
        )),
      ) as _i3.Future<_i2.HttpResponse>);

  @override
  _i3.Future<_i2.HttpResponse> delete(
    String? url, {
    Map<String, String>? headers,
    Map<String, dynamic>? body,
    Duration? timeout,
    String? apiVersion,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #timeout: timeout,
            #apiVersion: apiVersion,
          },
        ),
        returnValue: _i3.Future<_i2.HttpResponse>.value(_FakeHttpResponse_0(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #timeout: timeout,
              #apiVersion: apiVersion,
            },
          ),
        )),
      ) as _i3.Future<_i2.HttpResponse>);

  @override
  void addInterceptors(List<_i2.HttpInterceptor>? interceptors) =>
      super.noSuchMethod(
        Invocation.method(
          #addInterceptors,
          [interceptors],
        ),
        returnValueForMissingStub: null,
      );
}
