name: dependencies
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  logger: ^1.4.0
  equatable:
  http: ^1.1.0
  yaml: ^3.1.2
  go_router:
  flutter_svg:
  flutter_animate: ^4.1.1+1
  permission_handler: ^10.2.0
  provider: 
  dartz: ^0.10.1
  location: ^5.0.3
  fl_geocoder: ^0.1.0+1
  shared_preferences:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
